name: ml-app-workflow

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Access the repository
      uses: actions/checkout@v2

    - name: Install poetry
      uses: snok/install-poetry@v1

    - name: Install package
      run: poetry install

    - name: Build documentation
      run: poetry run make html --directory docs/

    - name: Add file to docs folder aviod Jekyll
      run: touch docs/build/html/.nojekyll

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.4.3
      with:
        branch: gh-pages
        folder: docs/build/html